import './globals.css'
import { B612_Mono   } from 'next/font/google'

const b612Mono = B612_Mono({
  subsets: ['latin'],
  variable: '--font-b612-mono',
  weight: ['400', '700'], // or any weights you need
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={b612Mono.variable}>{children}</body>
    </html>
  )
}
