import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { B612_Mono   } from 'next/font/google'
import Header from "./components/Header";
const b612Mono = B612_Mono({
  subsets: ['latin'],
  variable: '--font-b612-mono',
  weight: ['400', '700'], // or any weights you need
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
         className={b612Mono.variable}>
          <Header/>
          {children}
          </body>
    </html>
  );
}
